apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy-food-app
  namespace: healthyfood-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthy-food
  template:
    metadata:
      labels:
        app: healthy-food
    spec:
      containers:
        - name: healthy-food
          image: biled23/healthy-food-shop:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: POSTGRES_URL
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_URL):5432/$(POSTGRES_DB)"
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secrets

